import { NextRequest, NextResponse } from 'next/server'
// The warning generated by webpack can be disabled by setting:
// ignoreWarnings[].message = /Can't resolve 'coffee-script'/
/* eslint-disable-next-line global-require */
import {v2 as cloudinary} from 'cloudinary'

const UPLOAD_IMAGE_URL = process.env.UPLOAD_IMAGE_URL

export async function POST(
  req: NextRequest,
  res: NextResponse
) {
    try {
        const formData = req.body

        //cloudinary upload logic goes here

        return NextResponse.json({ message: 'Hello Everyone!' })
    } catch (e){
        console.log(e)
        return NextResponse.json({message: 'failed'})
    }
    
}